// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' ;
import 'package:flutter/foundation.dart';
//
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK32bolUbA26M09GnmES756ir_L5SyVYw',
    appId: '1:889278759383:web:0925944d77d0015d01cb92',
    messagingSenderId: '889278759383',
    projectId: 'signin-example-d58bd',
    authDomain: 'signin-example-d58bd.firebaseapp.com',
    storageBucket: 'signin-example-d58bd.appspot.com',
    measurementId: 'G-CVR5JKZY14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDdNLc2YRnxuQ1Tdv8WnpKXe1cLhqOQg',
    appId: '1:889278759383:android:709e045c4a37859201cb92',
    messagingSenderId: '889278759383',
    projectId: 'signin-example-d58bd',
    storageBucket: 'signin-example-d58bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSZNP8q_vl2OkFa4xW9s0P9g1Mt7UyIC0',
    appId: '1:889278759383:ios:7c613b37eb0fc25301cb92',
    messagingSenderId: '889278759383',
    projectId: 'signin-example-d58bd',
    storageBucket: 'signin-example-d58bd.appspot.com',
    iosClientId: '889278759383-edkj4o3qfh4870u5604pg38djo9rmgtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSZNP8q_vl2OkFa4xW9s0P9g1Mt7UyIC0',
    appId: '1:889278759383:ios:7c613b37eb0fc25301cb92',
    messagingSenderId: '889278759383',
    projectId: 'signin-example-d58bd',
    storageBucket: 'signin-example-d58bd.appspot.com',
    iosClientId: '889278759383-edkj4o3qfh4870u5604pg38djo9rmgtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
